### ISSUE TITLE
 Files being accumulated and not deleted

### ISSUE THREAD

**Issue by rishi-s8** [rishi-s8/cif-validator#14]
For validating, we’re saving the file and then passing it to the parser. Initially we were using the same name but #12 added random naming, hence we won’t have many overwrites. 

The files will keep accumulating at the server. 

We need to remove these files, either after every request, or keep the last, say 10 recent CIF files and then delete.

**Comment by Manvi07** [comment]
Would keeping the recent files help in any way? Also, someone might want to keep his data secure :/

**Comment by rishi-s8** [comment]
Making an open-source project, using some open-source tools and then hiding your data from the world? Doesn't seem right to me. Those are ```cif files``` which should be shown to everyone. 

But all this was my view. Depends on the requirements though. Let's keep this on hold until the next meeting.

**Comment by rishi-s8** [comment]
@Manvi07 In any case, the files being accumulated isn't a good sign. :)
